### ISSUE TITLE
Noobie needs help

### ISSUE THREAD

**Issue by roboroborobo** [sarnau/EnphaseEnergy#5]
Hi,
Just tried to run enphaseStreamMeter.py on Windows 10 with Python 3.10.2. Before running I edited the code to add Envoy host ip address and the installer password generated using the passwordCalc.py code.  Here's the error I get:
, line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Is this a configuration error with my (new) python installation or something else. 

Thanks in advance!
Robo

**Comment by sarnau** [comment]
You need to use `pip install requests` or `pip3 install requests`
